apiVersion: ray.io/v1alpha1
kind: RayService
metadata:
  name: ray-simple-api
spec:
  serviceUnhealthySecondThreshold: 900 # Config for the health check threshold for Ray Serve applications. Default value is 900.
  deploymentUnhealthySecondThreshold: 300 # Config for the health check threshold for Ray dashboard agent. Default value is 300.
  serveConfigV2: |
    applications:
      - name: simple_api
        import_path: simple_api.ray_app
        route_prefix: /
        runtime_env:
          working_dir: "https://github.com/Vibrat/test-ray-api/archive/refs/heads/main.zip"
          pip:
            - fastapi
        deployments:
          - name: SimpleAPI
            num_replicas: 1
            ray_actor_options:
              num_cpus: 1
              num_gpus: 0
            user_config: {}

  rayClusterConfig:
    rayVersion: "2.6.3"
    headGroupSpec:
      # The `rayStartParams` are used to configure the `ray start` command.
      # See https://github.com/ray-project/kuberay/blob/master/docs/guidance/rayStartParams.md for the default settings of `rayStartParams` in KubeRay.
      # See https://docs.ray.io/en/latest/cluster/cli.html#ray-start for all available options in `rayStartParams`.
      rayStartParams:
        dashboard-host: "0.0.0.0"
      #pod template
      template:
        spec:
          containers:
            - name: ray-head
              image: rayproject/ray:2.6.3
              # resources:
              #   limits:
              #     cpu: 500m
              #     memory: 512Mi
              #   requests:
              #     cpu: 250m
              #     memory: 256Mi
              ports:
                - containerPort: 6379
                  name: gcs-server
                - containerPort: 8265 # Ray dashboard
                  name: dashboard
                - containerPort: 10001
                  name: client
                - containerPort: 8000
                  name: serve
    workerGroupSpecs:
      # the pod replicas in this group typed worker
      - replicas: 1
        minReplicas: 1
        maxReplicas: 5
        # logical group name, for this called small-group, also can be functional
        groupName: small-group
        # The `rayStartParams` are used to configure the `ray start` command.
        # See https://github.com/ray-project/kuberay/blob/master/docs/guidance/rayStartParams.md for the default settings of `rayStartParams` in KubeRay.
        # See https://docs.ray.io/en/latest/cluster/cli.html#ray-start for all available options in `rayStartParams`.
        rayStartParams: {}
        #pod template
        template:
          spec:
            containers:
              - name: ray-worker # must consist of lower case alphanumeric characters or '-', and must start and end with an alphanumeric character (e.g. 'my-name',  or '123-abc'
                image: rayproject/ray:2.6.3
                lifecycle:
                  preStop:
                    exec:
                      command: ["/bin/sh", "-c", "ray stop"]
                # resources:
                #   limits:
                #     cpu: "500m"
                #     memory: "512Mi"
                #   requests:
                #     cpu: "250m"
                #     memory: "256Mi"
# # Add this Service definition to expose the Serve API
# apiVersion: v1
# kind: Service
# metadata:
#   name: ray-simple-api-svc
# spec:
#   type: NodePort  # or LoadBalancer if you're on a cloud provider
#   ports:
#     - port: 8000
#       targetPort: 8000
#       protocol: TCP
#       name: serve
#   selector:
#     ray.io/node-type: head
#     ray.io/cluster: ray-simple-api
